name: Build CI

on:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  fe_build:
    name: fe build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./FE"

    steps:
      - name: "Checkout"
      - uses: actions/checkout@v4
