name: Build CI

on:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  fe_build:
    name: fe build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./FE"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: "./FE"

      - name: Install
        run: npm install

      - name: Lint Test
        run: npm run lint

      - name: Build Test
        run: npm run build

  be_build:
    name: be build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./BE"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: "./BE"

      - name: Install
        run: npm install

      - name: Lint Test
        run: npm run lint

      - name: Build Test
        run: npm run build
